### PR TITLE
Add basic FFI interface using UniFFI

### PR DESCRIPTION
**Pull request by nesium**
As mentioned this is not rebased with the latest changes on master yet.

### CODE REVIEW

**Comment by valeriansaliou** [comment]
LGTM. Could you maybe wrap `prose_connect` and similar into a struct eg. `ProseMain`, if it's possible w/ the way FFIs work?

**Comment by nesium** [comment]
Unfortunately we can only provide global C-style functions as entrypoints for the FFI. What we could do however is convert the project into a [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html), put everything related to the FFI in its own crate and import the actual library from there.

**Comment by nesium** [comment]
Woops, it looks like that's actually wrong what I was saying. I'll try something.

**Comment by valeriansaliou** [comment]
Excellent Marc! A global HMap would be fine by me, I wanted to avoid that in the initial code design, but we may have no choice.

**Pull request merged**
